/**
 * Runtime configuration loaded from /config.js (generated by docker-entrypoint.sh).
 *
 * This provides environment variables that are NOT baked into the static build,
 * allowing the same Docker image to be configured differently per environment.
 *
 * Falls back to Vite build-time env vars (VITE_*) for development mode.
 */
interface RuntimeEnv {
  VITE_API_KEY?: string
}

declare global {
  interface Window {
    __ENV__?: RuntimeEnv
  }
}

function getApiKey(): string {
  // 1. Prefer runtime config (injected by docker-entrypoint.sh)
  if (window.__ENV__?.VITE_API_KEY) {
    return window.__ENV__.VITE_API_KEY
  }
  // 2. Fall back to Vite build-time env var (dev mode)
  if (import.meta.env.VITE_API_KEY) {
    return import.meta.env.VITE_API_KEY as string
  }
  return ''
}

export const config = {
  get apiKey() {
    return getApiKey()
  },
}
